### ISSUE TITLE
Quesiton on running time

### ISSUE THREAD

**Issue by NagisaZj** [yaoxt3/MILLION#3]
Hi, how long does it usually take to run MILLION?

I set up the environment as instructed, and ran `python3 ml10_language_instructions.py --log_dir=/data3/zj/MILLION/logs/ml10/language_instructions`. I used 80 CPU threads. Now the program has been running for over 24 hours, and it has used about 300M samples. I find that the script runs MILLION for 1e9 steps, which will take about 3 days. Is it a reasonable speed for running MILLION?

**Comment by zhenshan-bing** [comment]
This is a reasonable speed actually. It is indeed computational expensive.

**Comment by yaoxt3** [comment]
Hi, sorry for the late reply. Actually, we have to take 3 days for running the ML10 benckmark (4e8 steps) in V100 (16Gb) and 20 cores CPU.

**Comment by NagisaZj** [comment]
Thanks for the reply.
